--"Bookstore Database Schema and Sales Analytics Queries"

-- Create the Books table
CREATE TABLE Books (
    BookID INT PRIMARY KEY,
    Title NVARCHAR(255),
    Author NVARCHAR(255),
    Genre NVARCHAR(50),
    PublicationDate DATE,
    Price DECIMAL(10, 2)
);

-- Create the Customers table
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    Email NVARCHAR(255),
    JoinDate DATE
);

-- Create the Purchases table
CREATE TABLE Purchases (
    PurchaseID INT PRIMARY KEY,
    CustomerID INT,
    PurchaseDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- Create the PurchaseItems table
CREATE TABLE PurchaseItems (
    PurchaseItemID INT PRIMARY KEY,
    PurchaseID INT,
    BookID INT,
    Quantity INT,
    FOREIGN KEY (PurchaseID) REFERENCES Purchases(PurchaseID),
    FOREIGN KEY (BookID) REFERENCES Books(BookID)
);


-- 1. Find all customers who joined in the year 2023.
SELECT * 
FROM 
	Customers
WHERE 
	YEAR(JoinDate) = 2023

-- 2. List all books in the 'Dystopian' genre published before 1950.
SELECT * 
FROM 
	Books
WHERE 
	Genre = 'Dystopian' AND PublicationDate < '1950-01-01'

-- 3. Calculate the total number of books sold.
SELECT 
	SUM(QUANTITY) AS TotalBooksSold 
FROM 
	PurchaseItems

-- 4. Find the most expensive book purchased.
SELECT 
	TOP 1 b.BookID, b.Title
FROM 
	PurchaseItems P 
INNER JOIN 
	Books B ON P.BookID = B.BookID
ORDER BY 
	Price Desc

-- 5. List all books that have never been purchased.
SELECT 
	b.bookId, 
	b.Title
FROM 
	Books B 
LEFT JOIN 
	PurchaseItems P ON b.BookID = p.BookID
WHERE
	p.BookID IS NULL

-- 6. Calculate the total revenue generated by each book.
SELECT 
	b.bookId,
	b.Title,
	COALESCE(SUM(p.Quantity * b.Price),0) AS TotalRevenue
FROM 
	Books B 
LEFT JOIN 
	PurchaseItems P ON b.BookID = p.BookID
GROUP BY 
	b.BookID, b.Title

-- 7. Identify the top 3 best-selling books.
SELECT 
	TOP 3 p.BookId, 
	b.Title, 
	SUM(p.quantity) as TotalSales
FROM 
	PurchaseItems P
INNER JOIN 
	Books B ON P.BookID = b.BookID
GROUP BY 
	p.BookID, b.Title
ORDER BY 
	TotalSales Desc

-- 8. Find all customers who made purchases in the last 30 days.
SELECT C.customerId, 
	C.FirstName + ' ' + c.LastName AS FullName,
	p.PurchaseDate
FROM 
	Purchases P 
JOIN 
	Customers C ON p.CustomerID = c.CustomerID
WHERE 
	p.PurchaseDate 

-- 9. List all books purchased by more than 2 different customers.
SELECT 
	B.bookId, 
	b.Title 
FROM 
	PurchaseItems P
JOIN 
	Books B ON p.BookID = b.BookID
JOIN 
	Purchases pu ON p.PurchaseID = pu.PurchaseID
GROUP BY 
	b.bookId, 
	b.Title
HAVING 
	COUNT(DISTINCT pu.customerId) > 2

-- 10. Find the customer who has spent the most money.
SELECT 
	TOP 1 p.CustomerID,
	C.FirstName + ' ' + c.LastName AS FullName, 
	SUM(quantity * Price) as TotalSpent
FROM 
	PurchaseItems pu
JOIN 
	Purchases P on pU.PurchaseID = p.PurchaseID
JOIN 
	Customers c ON P.CustomerID = c.CustomerID
JOIN 
	Books B on pu.BookID = b.BookID
GROUP BY 
	p.CustomerID, c.FirstName, c.lastname 
ORDER BY 
	TotalSpent desc

-- 11. Calculate the average price of books purchased by each customer.
SELECT 
	P.CustomerID,
    C.FirstName + ' ' + C.LastName AS FullName,
    AVG(B.Price) AS AveragePrice
FROM 
	PurchaseItems P
JOIN 
	Purchases PU ON P.PurchaseID = PU.PurchaseID
JOIN 
	Books B ON P.BookID = B.BookID
JOIN 
	Customers C ON PU.CustomerID = C.CustomerID
GROUP BY 
	P.CustomerID, 
	C.FirstName, 
	C.LastName;

-- 12. List all books that have been purchased more than once.
SELECT B.BookID, 
       B.Title
FROM 
	PurchaseItems P
JOIN 
	Books B ON P.BookID = B.BookID
GROUP BY 
	B.BookID, 
	B.Title
HAVING 
	SUM(P.Quantity) > 1;

-- 13. Find customers who have purchased books from multiple genres.
SELECT c.CustomerID,
	C.FirstName + ' ' + c.LastName AS FullName 
FROM 
	PurchaseItems p
JOIN 
	Purchases pu ON p.PurchaseID = pu.PurchaseID
JOIN 
	Customers C ON pu.CustomerID = c.CustomerID
JOIN 
	Books b ON p.BookID = b.BookID
GROUP BY 
	c.CustomerID, c.FirstName, c.LastName
HAVING 
	COUNT(DISTINCT genre) > 1

-- 14. Identify the author with the highest total revenue.
SELECT 
	TOP 1 b.Author, SUM(QUANTITY*PRICE) AS TotalRevenue
FROM 
	PurchaseItems P
JOIN 
	Books B on  p.BookID = b.BookID
GROUP BY 
	b.Author
ORDER BY 
	TotalRevenue desc
